

import "./globals.css";
import localFont from 'next/font/local'


const myFont = localFont({
  src: '../public/font/tanha.ttf',
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="fa" dir="rtl" className={myFont.className}
    >
      <body className="min-h-full flex flex-col">


          <main>
            {children}
          </main>

      </body>
    </html>
  );
}
