

import "./globals.css";
import localFont from 'next/font/local'
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const myFont = localFont({
  src: '../public/font/tanha.ttf',
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="fa"
      dir="rtl"
      className={cn(myFont.className, "font-sans", inter.variable)}
    >
      <body className="min-h-full flex flex-col">
        <main>{children}</main>
        <Toaster position="top-right" richColors={true} />
      </body>
    </html>
  );
}
