const products = [
  {
    name: "پیراهن دکمه‌دار کلاسیک آکسفورد",
    description:
      "این پیراهن کلاسیک آکسفورد برای ظاهری آراسته و در عین حال راحت طراحی شده است. تولید شده از پنبه باکیفیت، دارای یقه دکمه‌دار و برشی راحت و آزاد است. ایده‌آل برای موقعیت‌های رسمی و روزمره، همراه با آستین‌های بلند، سجاف دکمه‌دار و برش پشت. پیراهن با لبه پایینی ملایم و هلال و سرآستین‌های دکمه‌دار قابل تنظیم تکمیل شده است.",
    price: 39.99,
    discountPrice: 34.99,
    countInStock: 20,
    sku: "OX-SH-001",
    category: "Top Wear",
    brand: "Urban Threads",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["قرمز", "آبی", "زرد"],
    collections: "Business Casual",
    material: "Cotton",
    gender: "Men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=39",
        altText: "Classic Oxford Button-Down Shirt Front View",
      },
      {
        url: "https://picsum.photos/500/500?random=40",
        altText: "Classic Oxford Button-Down Shirt Back View",
      },
    ],
    rating: 4.5,
    numReviews: 12,
  },
  {
    name: "پیراهن کشی جذب (اسلیم فیت)",
    description:
      "یک پیراهن جذب و چندمنظوره، عالی برای قرارهای کاری یا مهمانی‌های شبانه. طراحی شده با اندامی فیت، که خاصیت کشسانی افزوده شده به آن، حداکثر راحتی را در طول روز فراهم می‌کند. دارای یقه برگردان آهاردار، سجاف دکمه‌دار و سرآستین‌های قابل تنظیم.",
    price: 29.99,
    discountPrice: 24.99,
    countInStock: 35,
    sku: "SLIM-SH-002",
    category: "Top Wear",
    brand: "Modern Fit",
    sizes: ["S", "M", "L", "XL"],
    colors: ["مشکی", "سرمه‌ای", "زرشکی"],
    collections: "Formal Wear",
    material: "Cotton Blend",
    gender: "Men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=41",
        altText: "Slim-Fit Stretch Shirt Front View",
      },
      {
        url: "https://picsum.photos/500/500?random=42",
        altText: "Slim-Fit Stretch Shirt Back View",
      },
    ],
    rating: 4.8,
    numReviews: 15,
  },
  {
    name: "پیراهن جین کژوال",
    description:
      "این پیراهن جین راحت از پارچه جین پنبه‌ای سبک ساخته شده است. دارای تن‌خور معمولی (راسته)، دکمه‌های فشاری و لبه پایینی صاف است. با جزئیات الهام‌گرفته از استایل وسترن، این پیراهن برای پوشیدن روی تیشرت یا به تنهایی عالی است.",
    price: 49.99,
    discountPrice: 44.99,
    countInStock: 15,
    sku: "CAS-DEN-003",
    category: "Top Wear",
    brand: "Street Style",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["آبی روشن", "جین تیره سنگ‌شور"],
    collections: "Casual Wear",
    material: "Denim",
    gender: "Men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=43",
        altText: "Casual Denim Shirt Front View",
      },
      {
        url: "https://picsum.photos/500/500?random=44",
        altText: "Casual Denim Shirt Back View",
      },
    ],
    rating: 4.6,
    numReviews: 8,
  },
  {
    name: "پیراهن هاوایی طرح‌دار (ریزورت)",
    description:
      "این پیراهن طرح‌دار که برای تابستان طراحی شده، برای تعطیلات یا سفرهای آخر هفته عالی است. دارای تن‌خور آزاد، آستین‌های کوتاه و یقه کوبایی (کمپ) است. طرح استوایی سرتاسری آن حس و حالی شاد و پرانرژی می‌بخشد.",
    price: 29.99,
    discountPrice: 22.99,
    countInStock: 25,
    sku: "PRNT-RES-004",
    category: "Top Wear",
    brand: "Beach Breeze",
    sizes: ["S", "M", "L", "XL"],
    colors: ["طرح استوایی", "هاوایی سرمه‌ای"],
    collections: "Vacation Wear",
    material: "Viscose",
    gender: "Men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=45",
        altText: "Printed Resort Shirt Front View",
      },
      {
        url: "https://picsum.photos/500/500?random=1",
        altText: "Printed Resort Shirt Back View",
      },
    ],
    rating: 4.4,
    numReviews: 10,
  },
  {
    name: "پیراهن جذب با اتوکشی آسان (Easy-Iron)",
    description:
      "یک پیراهن جذب با ویژگی اتوکشی آسان از پارچه پنبه‌ای بافت‌دار با برشی اندامی. دارای یقه برگردان، سجاف دکمه‌دار کلاسیک و برش پشت. آستین‌های بلند و سرآستین‌های دکمه‌دار قابل تنظیم همراه با لبه هلال پایینی.",
    price: 34.99,
    discountPrice: 29.99,
    countInStock: 30,
    sku: "SLIM-EIR-005",
    category: "Top Wear",
    brand: "Urban Chic",
    sizes: ["S", "M", "L", "XL"],
    colors: ["سفید", "خاکستری"],
    collections: "Business Wear",
    material: "Cotton",
    gender: "Men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=47",
        altText: "Slim-Fit Easy-Iron Shirt Front View",
      },
      {
        url: "https://picsum.photos/500/500?random=2",
        altText: "Slim-Fit Easy-Iron Shirt Front View",
      },
    ],
    rating: 5,
    numReviews: 14,
  },
  {
    name: "تیشرت یقه پولوشرت با بافت کشبافت",
    description:
      "یک لباس کلاسیک برای کمد لباس شما؛ این تیشرت پولوشرت دارای یقه و سرآستین‌های کشبافت است. ساخته شده از ۱۰۰٪ پنبه، خنکی و راحتی را در طول روز تضمین می‌کند. برش جذب با سجاف دکمه‌دار در قسمت یقه.",
    price: 24.99,
    discountPrice: 19.99,
    countInStock: 50,
    sku: "POLO-TSH-006",
    category: "Top Wear",
    brand: "Polo Classics",
    sizes: ["S", "M", "L", "XL"],
    colors: ["سفید", "سرمه‌ای", "قرمز"],
    collections: "Casual Wear",
    material: "Cotton",
    gender: "Men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=3",
        altText: "Polo T-Shirt Front View",
      },
      {
        url: "https://picsum.photos/500/500?random=4",
        altText: "Polo T-Shirt Back View",
      },
    ],
    rating: 4.3,
    numReviews: 22,
  },
  {
    name: "تیشرت لش (اُوِرسایز) طرح‌دار",
    description:
      "یک تیشرت اورسایز گرافیکی که راحتی را با استایل خیابانی تلفیق می‌کند. با چاپ‌های جسورانه روی سینه، این تیشرت لش حال و هوایی مدرن دارد و برای ست کردن با شلوار جین یا اسلش عالی است.",
    price: 19.99,
    discountPrice: 15.99,
    countInStock: 40,
    sku: "OVS-GRF-007",
    category: "Top Wear",
    brand: "Street Vibes",
    sizes: ["S", "M", "L", "XL"],
    colors: ["مشکی", "خاکستری"],
    collections: "Streetwear",
    material: "Cotton",
    gender: "Men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=5",
        altText: "Oversized Graphic T-Shirt Front View",
      },
    ],
    rating: 4.6,
    numReviews: 30,
  },
  {
    name: "پیراهن یقه هنلی با تن‌خور معمولی",
    description:
      "نگاهی مدرن به پیراهن کلاسیک هنلی (یقه گرد دکمه‌دار)؛ این مدل دارای سجاف دکمه‌دار و مچ‌های کشبافت است. ساخته شده از مخلوط پنبه نرم با کمی الاستین جهت ایجاد خاصیت کشسانی.",
    price: 22.99,
    discountPrice: 18.99,
    countInStock: 35,
    sku: "REG-HEN-008",
    category: "Top Wear",
    brand: "Heritage Wear",
    sizes: ["S", "M", "L", "XL"],
    colors: ["طوسی ملانژ", "زیتونی", "مشکی"],
    collections: "Casual Wear",
    material: "Cotton Blend",
    gender: "Men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=6",
        altText: "Regular-Fit Henley Shirt Front View",
      },
    ],
    rating: 4.5,
    numReviews: 25,
  },
  {
    name: "تیشرت آستین بلند حرارتی (بافت وافلی)",
    description:
      "با این تیشرت حرارتی آستین بلند که از پنبه نرم با بافت وافلی ساخته شده، گرم بمانید. ایده‌آل برای پوشیدن لایه‌ای در ماه‌های سرد سال؛ طراحی جذب آن تناسب اندام راحت و گرمی را تضمین می‌کند.",
    price: 27.99,
    discountPrice: 22.99,
    countInStock: 20,
    sku: "LST-THR-009",
    category: "Top Wear",
    brand: "Winter Basics",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["زغالی", "سبز تیره", "سرمه‌ای"],
    collections: "Winter Essentials",
    material: "Cotton",
    gender: "Men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=7",
        altText: "Long-Sleeve Thermal Tee Front View",
      },
    ],
    rating: 4.4,
    numReviews: 18,
  },
  {
    name: "تیشرت کلاسیک یقه هفت",
    description:
      "یک تیشرت یقه هفت کلاسیک برای استفاده روزمره. این تیشرت با تن‌خور معمولی از پنبه خنک ساخته شده و طراحی ساده و تمیزی با یقه هفت جذاب دارد. پارچه سبک و بافت نرم آن را برای استایل‌های کژوال عالی کرده است.",
    price: 14.99,
    discountPrice: 11.99,
    countInStock: 60,
    sku: "VNECK-CLS-010",
    category: "Top Wear",
    brand: "Everyday Comfort",
    sizes: ["S", "M", "L", "XL"],
    colors: ["سفید", "مشکی", "سرمه‌ای"],
    collections: "Basics",
    material: "Cotton",
    gender: "Men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=8",
        altText: "V-Neck Classic T-Shirt Front View",
      },
    ],
    rating: 4.7,
    numReviews: 28,
  },
  {
    name: "شلوار اسلش جذب (اسلیم فیت)",
    description:
      "شلوار اسلش جذب با کمر کشی بنددار. دارای مچ‌های کشبافت و جیب‌های جانبی. ایده‌آل برای گشت‌وگذارهای روزمره یا ورزش کردن.",
    price: 40,
    discountPrice: 35,
    countInStock: 20,
    sku: "BW-001",
    category: "Bottom Wear",
    brand: "ActiveWear",
    sizes: ["S", "M", "L", "XL"],
    colors: ["مشکی", "خاکستری", "سرمه‌ای"],
    collections: "Casual Collection",
    material: "Cotton Blend",
    gender: "Men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=9",
        altText: "Slim Fit Joggers Front View",
      },
    ],
    rating: 4.5,
    numReviews: 12,
  },
  {
    name: "شلوار اسلش کارگو (شش‌جیب)",
    description:
      "شلوار اسلش کارگو با تن‌خور آزاد و جیب‌های متعدد برای کاربرد بیشتر. دارای کمر بنددار و دم‌پای کش‌دار برای ظاهری مدرن.",
    price: 45,
    discountPrice: 40,
    countInStock: 15,
    sku: "BW-002",
    category: "Bottom Wear",
    brand: "UrbanStyle",
    sizes: ["S", "M", "L", "XL"],
    colors: ["زیتونی", "مشکی"],
    collections: "Urban Collection",
    material: "Cotton",
    gender: "Men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=10",
        altText: "Cargo Joggers Front View",
      },
    ],
    rating: 4.7,
    numReviews: 20,
  },
  {
    name: "شلوار خانگی خمره‌ای (مخروطی)",
    description:
      "شلوار ورزشی و خانگی خمره‌ای طراحی شده برای راحتی. کمر کشی با بند قابل تنظیم، عالی برای استراحت در خانه یا فعالیت‌های ورزشی.",
    price: 35,
    discountPrice: 30,
    countInStock: 25,
    sku: "BW-003",
    category: "Bottom Wear",
    brand: "ChillZone",
    sizes: ["S", "M", "L", "XL"],
    colors: ["خاکستری", "زغالی", "آبی"],
    collections: "Lounge Collection",
    material: "Fleece",
    gender: "Men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=11",
        altText: "Tapered Sweatpants Front View",
      },
    ],
    rating: 4.3,
    numReviews: 18,
  },
  {
    name: "شلوار جین دنیم",
    description:
      "شلوار جین کلاسیک اسلیم‌فیت با کمی خاصیت کشسانی برای راحتی بیشتر. دارای زیپ و استایل پنج جیب برای ظاهری ماندگار و همیشگی.",
    price: 60,
    discountPrice: 50,
    countInStock: 30,
    sku: "BW-004",
    category: "Bottom Wear",
    brand: "DenimCo",
    sizes: ["S", "M", "L", "XL"],
    colors: ["آبی تیره", "آبی روشن"],
    collections: "Denim Collection",
    material: "Denim",
    gender: "Men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=12",
        altText: "Denim Jeans Front View",
      },
    ],
    rating: 4.6,
    numReviews: 22,
  },
  {
    name: "شلوار کتان چینو (Chino)",
    description:
      "شلوار چینو جذب ساخته شده از پارچه کتان کج‌راه کشی. دارای دکمه و جیب‌های جلو و عقب. ایده‌آل برای استایل‌های روزمره و نیمه‌رسمی.",
    price: 55,
    discountPrice: 48,
    countInStock: 40,
    sku: "BW-005",
    category: "Bottom Wear",
    brand: "CasualLook",
    sizes: ["S", "M", "L", "XL"],
    colors: ["کرم (بژ)", "سرمه‌ای", "مشکی"],
    collections: "Smart Casual Collection",
    material: "Cotton",
    gender: "Men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=13",
        altText: "Chino Pants Front View",
      },
    ],
    rating: 4.8,
    numReviews: 15,
  },
  {
    name: "شلوار ورزشی خط‌دار (ترک‌پنتس)",
    description:
      "شلوار ورزشی راحت با کمر کشی و ساق‌های خمره‌ای. دارای خطوط جانبی برای ظاهری اسپرت. مناسب برای فعالیت‌های ورزشی و استفاده روزمره.",
    price: 40,
    discountPrice: 35,
    countInStock: 20,
    sku: "BW-006",
    category: "Bottom Wear",
    brand: "SportX",
    sizes: ["S", "M", "L", "XL"],
    colors: ["مشکی", "قرمز", "آبی"],
    collections: "Activewear Collection",
    material: "Polyester",
    gender: "Men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=14",
        altText: "Track Pants Front View",
      },
    ],
    rating: 4.2,
    numReviews: 17,
  },
  {
    name: "شلوار پارچه‌ای جذب (اسلیم فیت)",
    description:
      "شلوار پارچه‌ای خوش‌دوخت و جذب همراه با پل کمربند و قزن. مناسب برای موقعیت‌های رسمی یا استایل‌های کژوال شیک.",
    price: 65,
    discountPrice: 55,
    countInStock: 15,
    sku: "BW-007",
    category: "Bottom Wear",
    brand: "ExecutiveStyle",
    sizes: ["M", "L", "XL"],
    colors: ["خاکستری", "مشکی"],
    collections: "Office Wear",
    material: "Polyester",
    gender: "Men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=15",
        altText: "Slim Fit Trousers Front View",
      },
    ],
    rating: 4.7,
    numReviews: 10,
  },
  {
    name: "شلوار کارگو (شش‌جیب) آزاد",
    description:
      "شلوار کارگو با تن‌خور آزاد و جیب‌های کاربردی متعدد. دارای مچ پا قابل تنظیم و کمر بنددار جهت تطبیق‌پذیری و راحتی بیشتر.",
    price: 50,
    discountPrice: 45,
    countInStock: 25,
    sku: "BW-008",
    category: "Bottom Wear",
    brand: "StreetWear",
    sizes: ["S", "M", "L", "XL"],
    colors: ["زیتونی", "قهوه‌ای", "مشکی"],
    collections: "Street Style Collection",
    material: "Cotton",
    gender: "Men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=16",
        altText: "Cargo Pants Front View",
      },
    ],
    rating: 4.5,
    numReviews: 13,
  },
  {
    name: "شلوار اسلش راحتی آزاد",
    description:
      "شلوار راحتی با تن‌خور آزاد ساخته شده از پارچه دورس نرم. دارای کمر کشی و بند قابل تنظیم برای تنظیم اندازه دلخواه.",
    price: 35,
    discountPrice: 30,
    countInStock: 35,
    sku: "BW-009",
    category: "Bottom Wear",
    brand: "LoungeWear",
    sizes: ["S", "M", "L", "XL"],
    colors: ["خاکستری", "مشکی", "سرمه‌ای"],
    collections: "Lounge Collection",
    material: "Fleece",
    gender: "Men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=17",
        altText: "Relaxed Fit Sweatpants Front View",
      },
    ],
    rating: 4.3,
    numReviews: 14,
  },
  {
    name: "شلوار پارچه‌ای رسمی کلاسیک",
    description:
      "شلوار پارچه‌ای رسمی کلاسیک با تن‌خور جذب. ساخته شده از پارچه‌ای سبک و ضدچروک برای ظاهری آراسته در دفتر کار یا مراسم‌های رسمی.",
    price: 70,
    discountPrice: 60,
    countInStock: 20,
    sku: "BW-010",
    category: "Bottom Wear",
    brand: "ElegantStyle",
    sizes: ["M", "L", "XL"],
    colors: ["مشکی", "سرمه‌ای"],
    collections: "Formal Collection",
    material: "Polyester",
    gender: "Men",
    images: [
      {
        url: "https://picsum.photos/500/500?random=18",
        altText: "Formal Dress Pants Front View",
      },
    ],
    rating: 4.9,
    numReviews: 8,
  },
  {
    name: "شلوار جین اسکینی فاق بلند",
    description:
      "شلوار جین اسکینی فاق بلند از جنس دنیم کشی با دکمه و زیپ. دارای تن‌خوری جذاب که انحنای بدن را به‌خوبی نشان می‌دهد و اندام را زیباتر جلوه می‌دهد.",
    price: 50,
    discountPrice: 45,
    countInStock: 30,
    sku: "BW-W-001",
    category: "Bottom Wear",
    brand: "DenimStyle",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["آبی تیره", "مشکی", "آبی روشن"],
    collections: "Denim Collection",
    material: "Denim",
    gender: "Women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=19",
        altText: "High-Waist Skinny Jeans",
      },
    ],
    rating: 4.8,
    numReviews: 20,
  },
  {
    name: "شلوار پارچه‌ای بگ (گشاد)",
    description:
      "شلوار لَخت و گشاد با فاق بلند و جیب‌های جانبی. عالی برای یک استایل شیک که راحتی و جذابیت را هم‌زمان ترکیب می‌کند.",
    price: 60,
    discountPrice: 55,
    countInStock: 25,
    sku: "BW-W-002",
    category: "Bottom Wear",
    brand: "ElegantWear",
    sizes: ["S", "M", "L", "XL"],
    colors: ["کرم (بژ)", "مشکی", "سفید"],
    collections: "Formal Collection",
    material: "Polyester",
    gender: "Women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=20",
        altText: "Wide-Leg Trousers Front View",
      },
    ],
    rating: 4.7,
    numReviews: 15,
  },
  {
    name: "لگینگ کشی راحت",
    description:
      "لگینگ نرم و کشی با فاق بلند. عالی برای استراحت، ورزش یا پوشش روزمره، با تن‌خوری صاف و یکدست که به زیبایی روی بدن می‌نشیند.",
    price: 25,
    discountPrice: 20,
    countInStock: 40,
    sku: "BW-W-003",
    category: "Bottom Wear",
    brand: "ComfyFit",
    sizes: ["S", "M", "L", "XL"],
    colors: ["مشکی", "خاکستری", "سرمه‌ای"],
    collections: "Activewear Collection",
    material: "Cotton Blend",
    gender: "Women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=21",
        altText: "Stretch Leggings Front View",
      },
    ],
    rating: 4.5,
    numReviews: 30,
  },
  {
    name: "دامن میدی پلیسه",
    description:
      "دامن میدی پلیسه شیک با کمر پهن فاق بلند و پارچه‌ای نرم که ریزش بسیار زیبایی دارد. ایده‌آل برای موقعیت‌های رسمی و روزمره.",
    price: 55,
    discountPrice: 50,
    countInStock: 20,
    sku: "BW-W-004",
    category: "Bottom Wear",
    brand: "ChicStyle",
    sizes: ["S", "M", "L"],
    colors: ["صورتی", "سرمه‌ای", "مشکی"],
    collections: "Spring Collection",
    material: "Polyester",
    gender: "Women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=22",
        altText: "Pleated Midi Skirt Front View",
      },
    ],
    rating: 4.6,
    numReviews: 18,
  },
  {
    name: "شلوار دامن کلوش (پالازو)",
    description:
      "شلوار پالازو فاق بلند با تن‌خور آزاد و رها. راحت و شیک، که آن را برای گشت‌وگذار روزمره یا روزهای ساحلی عالی می‌کند.",
    price: 45,
    discountPrice: 40,
    countInStock: 35,
    sku: "BW-W-005",
    category: "Bottom Wear",
    brand: "BreezyVibes",
    sizes: ["S", "M", "L", "XL"],
    colors: ["سفید", "کرم (بژ)", "آبی روشن"],
    collections: "Summer Collection",
    material: "Linen Blend",
    gender: "Women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=23",
        altText: "Flared Palazzo Pants Front View",
      },
    ],
    rating: 4.4,
    numReviews: 22,
  },
  {
    name: "شلوار اسلش فاق بلند",
    description:
      "شلوار اسلش فاق بلند و راحت با کمر کشی و بند برای ایستایی بی‌نقص. عالی برای استراحت در خانه یا تمرینات ورزشی.",
    price: 40,
    discountPrice: 35,
    countInStock: 30,
    sku: "BW-W-006",
    category: "Bottom Wear",
    brand: "ActiveWear",
    sizes: ["XS", "S", "M", "L"],
    colors: ["مشکی", "خاکستری", "صورتی"],
    collections: "Loungewear Collection",
    material: "Cotton Blend",
    gender: "Women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=24",
        altText: "High-Rise Joggers Front View",
      },
    ],
    rating: 4.3,
    numReviews: 25,
  },
  {
    name: "شورتک کمربنددار مدل پیپربگ (Paperbag)",
    description:
      "شورتک شیک مدل پیپربگ با کمر چین‌دار کمربنددار و پاهای آزاد. عالی برای تفریحات تابستانی و خنک ماندن با استایلی خاص.",
    price: 35,
    discountPrice: 30,
    countInStock: 20,
    sku: "BW-W-007",
    category: "Bottom Wear",
    brand: "SunnyStyle",
    sizes: ["S", "M", "L"],
    colors: ["سفید", "خاکی", "آبی"],
    collections: "Summer Collection",
    material: "Cotton",
    gender: "Women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=25",
        altText: "Paperbag Waist Shorts Front View",
      },
    ],
    rating: 4.5,
    numReviews: 19,
  },
  {
    name: "شورتک جین کشی",
    description:
      "شورتک جین کشی راحت با فاق بلند و لبه زاپ‌دار ریش‌ریش. عالی برای ست کردن با تاپ‌های محبوب شما در ماه‌های گرم سال.",
    price: 40,
    discountPrice: 35,
    countInStock: 25,
    sku: "BW-W-008",
    category: "Bottom Wear",
    brand: "DenimStyle",
    sizes: ["S", "M", "L", "XL"],
    colors: ["آبی", "مشکی", "سفید"],
    collections: "Denim Collection",
    material: "Denim",
    gender: "Women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=26",
        altText: "Stretch Denim Shorts Front View",
      },
    ],
    rating: 4.7,
    numReviews: 15,
  },
  {
    name: "شلوارک دامن‌نما (کولوت)",
    description:
      "شلوارک گشاد مدل دامن‌نما با فاق بلند جذاب و قد برمودا (کوتاه). ترکیبی عالی از راحتی و استایل برای هر موقعیت روزمره.",
    price: 50,
    discountPrice: 45,
    countInStock: 30,
    sku: "BW-W-009",
    category: "Bottom Wear",
    brand: "ChicStyle",
    sizes: ["S", "M", "L", "XL"],
    colors: ["مشکی", "سفید", "زیتونی"],
    collections: "Casual Collection",
    material: "Polyester",
    gender: "Women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=27",
        altText: "Culottes Front View",
      },
    ],
    rating: 4.6,
    numReviews: 23,
  },
  {
    name: "شلوار پارچه‌ای پیله‌دار کلاسیک",
    description:
      "شلوار پیله‌دار اصیل و همیشگی با دوخت ظریف و فیت. یکی از ضروریات کمد لباس برای پوشش اداری یا موقعیت‌های رسمی.",
    price: 70,
    discountPrice: 65,
    countInStock: 25,
    sku: "BW-W-010",
    category: "Bottom Wear",
    brand: "ElegantWear",
    sizes: ["S", "M", "L", "XL"],
    colors: ["سرمه‌ای", "مشکی", "خاکستری"],
    collections: "Formal Collection",
    material: "Wool Blend",
    gender: "Women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=28",
        altText: "Classic Pleated Trousers Front View",
      },
    ],
    rating: 4.8,
    numReviews: 20,
  },
  {
    name: "نیم‌تنه بافتنی کراپ",
    description:
      "یک نیم‌تنه بافتنی شیک و کراپ با اندامی جذب و زیبا. عالی برای ست کردن با شلوارهای جین فاق بلند یا دامن برای داشتن استایلی کژوال.",
    price: 40,
    discountPrice: 35,
    countInStock: 25,
    sku: "TW-W-001",
    category: "Top Wear",
    brand: "ChicKnit",
    sizes: ["S", "M", "L"],
    colors: ["کرم (بژ)", "سفید"],
    collections: "Knits Collection",
    material: "Cotton Blend",
    gender: "Women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=29",
        altText: "Knitted Cropped Top",
      },
    ],
    rating: 4.6,
    numReviews: 15,
  },
  {
    name: "بلوز گل‌دار بوهو (Boho)",
    description:
      "بلوز لخت و سبک بوهو با طرح‌های گل‌دار، دارای تن‌خور آزاد و آستین‌های پفی مچ‌دار. ایده‌آل برای روزهای خنک تابستانی.",
    price: 50,
    discountPrice: 45,
    countInStock: 30,
    sku: "TW-W-002",
    category: "Top Wear",
    brand: "BohoVibes",
    sizes: ["S", "M", "L", "XL"],
    colors: ["سفید", "صورتی"],
    collections: "Summer Collection",
    material: "Viscose",
    gender: "Women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=30",
        altText: "Boho Floral Blouse",
      },
    ],
    rating: 4.7,
    numReviews: 20,
  },
  {
    name: "تیشرت کژوال روزمره",
    description:
      "یک تیشرت روزمره نرم و خنک با تن‌خور کلاسیک. دارای یقه گرد و آستین‌های کوتاه، عالی برای پوشش روزانه.",
    price: 25,
    discountPrice: 20,
    countInStock: 50,
    sku: "TW-W-003",
    category: "Top Wear",
    brand: "ComfyTees",
    sizes: ["S", "M", "L", "XL"],
    colors: ["مشکی", "سفید", "خاکستری"],
    collections: "Essentials",
    material: "Cotton",
    gender: "Women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=31",
        altText: "Casual T-Shirt",
      },
    ],
    rating: 4.5,
    numReviews: 25,
  },
  {
    name: "تاپ یقه قایقی (آف‌شولدر)",
    description:
      "یک تاپ یقه قایقی شیک با آستین‌های چین‌دار کلوش و تن‌خوری جذاب. ایده‌آل برای افزودن ظرافت و حس زنانگی به استایل شما.",
    price: 45,
    discountPrice: 40,
    countInStock: 35,
    sku: "TW-W-004",
    category: "Top Wear",
    brand: "Elegance",
    sizes: ["S", "M", "L"],
    colors: ["قرمز", "سفید", "آبی"],
    collections: "Evening Collection",
    material: "Polyester",
    gender: "Women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=32",
        altText: "Off-Shoulder Top",
      },
    ],
    rating: 4.7,
    numReviews: 18,
  },
  {
    name: "تاپ بندی با لبه توری (کمی‌سول)",
    description:
      "یک تاپ بندی ظریف با تزیینات توری و بندهای قابل تنظیم. پارچه سبک آن، این تاپ را برای پوشیدن زیر لباس‌های دیگر یا به تنهایی در هوای گرم عالی می‌کند.",
    price: 35,
    discountPrice: 30,
    countInStock: 40,
    sku: "TW-W-005",
    category: "Top Wear",
    brand: "DelicateWear",
    sizes: ["S", "M", "L"],
    colors: ["مشکی", "سفید"],
    collections: "Lingerie-Inspired",
    material: "Silk Blend",
    gender: "Women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=33",
        altText: "Lace-Trimmed Cami Top",
      },
    ],
    rating: 4.8,
    numReviews: 22,
  },
  {
    name: "تیشرت با چاپ گرافیکی",
    description:
      "یک تیشرت ترندی با چاپ گرافیکی و تن‌خور آزاد. آن را با شلوار جین یا دامن ست کنید تا استایلی جذاب و کژوال داشته باشید.",
    price: 30,
    discountPrice: 25,
    countInStock: 45,
    sku: "TW-W-006",
    category: "Top Wear",
    brand: "StreetStyle",
    sizes: ["S", "M", "L", "XL"],
    colors: ["سفید", "مشکی"],
    collections: "Urban Collection",
    material: "Cotton",
    gender: "Women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=34",
        altText: "Graphic Print Tee",
      },
    ],
    rating: 4.6,
    numReviews: 30,
  },
  {
    name: "تاپ آستین بلند کبریتی (کشبافت ریز)",
    description:
      "یک تاپ آستین بلند گرم و نرم با بافت کبریتی که راحتی و استایل را هم‌زمان هدیه می‌دهد. عالی برای پوشش لایه‌ای در ماه‌های سرد سال.",
    price: 55,
    discountPrice: 50,
    countInStock: 30,
    sku: "TW-W-007",
    category: "Top Wear",
    brand: "ComfortFit",
    sizes: ["S", "M", "L", "XL"],
    colors: ["خاکستری", "صورتی", "قهوه‌ای"],
    collections: "Fall Collection",
    material: "Cotton Blend",
    gender: "Women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=35",
        altText: "Ribbed Long-Sleeve Top",
      },
    ],
    rating: 4.7,
    numReviews: 26,
  },
  {
    name: "بلوز با آستین‌های چین‌دار কلوش",
    description:
      "یک بلوز سبک با آستین‌های چین‌دار ظریف و تن‌خوری زیبا. عالی برای بخشیدن ظاهری لطیف و زنانه به هر استایلی.",
    price: 45,
    discountPrice: 40,
    countInStock: 20,
    sku: "TW-W-008",
    category: "Top Wear",
    brand: "FeminineWear",
    sizes: ["S", "M", "L"],
    colors: ["سفید", "سرمه‌ای", "یاسی (اسطوخودوس)"],
    collections: "Summer Collection",
    material: "Viscose",
    gender: "Women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=36",
        altText: "Ruffle-Sleeve Blouse",
      },
    ],
    rating: 4.5,
    numReviews: 19,
  },
  {
    name: "شومیز دکمه‌دار کلاسیک زنانه",
    description:
      "یک شومیز دکمه‌دار چندمنظوره که هم در استایل‌های رسمی و هم کژوال کاربرد دارد. ساخته شده از پارچه‌ای نرم با برشی اندامی و خوش‌دوخت.",
    price: 60,
    discountPrice: 55,
    countInStock: 25,
    sku: "TW-W-009",
    category: "Top Wear",
    brand: "ClassicStyle",
    sizes: ["S", "M", "L", "XL"],
    colors: ["سفید", "آبی روشن", "مشکی"],
    collections: "Office Collection",
    material: "Cotton",
    gender: "Women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=37",
        altText: "Classic Button-Up Shirt",
      },
    ],
    rating: 4.8,
    numReviews: 25,
  },
  {
    name: "تاپ چپ و راستی یقه هفت (مدل رپ)",
    description:
      "یک تاپ شیک یقه هفت با طراحی چپ و راستی و بند دور کمر. استایل ظریف آن، این تاپ را برای مناسبت‌های روزمره و نیمه‌رسمی عالی می‌کند.",
    price: 50,
    discountPrice: 45,
    countInStock: 30,
    sku: "TW-W-010",
    category: "Top Wear",
    brand: "ChicWrap",
    sizes: ["S", "M", "L"],
    colors: ["قرمز", "مشکی", "سفید"],
    collections: "Evening Collection",
    material: "Polyester",
    gender: "Women",
    images: [
      {
        url: "https://picsum.photos/500/500?random=38",
        altText: "V-Neck Wrap Top",
      },
    ],
    rating: 4.7,
    numReviews: 22,
  },
];

module.exports = products;
